version: '3.8'

services:
  sda-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sda-admin-panel
    ports:
      - "8001:8001"
    environment:
      # Database Configuration - Connect to existing SDA database
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_SERVER=${POSTGRES_SERVER:-localhost}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-sda_db}
      
      # Django Settings
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      
      # Static and Media settings
      - STATIC_URL=/static/
      - STATIC_ROOT=/app/staticfiles
      - MEDIA_URL=/media/
      - MEDIA_ROOT=/app/media
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      # Mount the uploads directory from your FastAPI backend for file compatibility
      - ../sda/uploads:/app/backend_uploads:ro
    networks:
      - default
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
