version: '3.8'

services:
  sda-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sda-admin-panel-simple
    ports:
      - "8001:8001"
    environment:
      # Database Configuration
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-sda_db}
      
      # Django Settings
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      
      # Static and Media settings
      - STATIC_URL=/static/
      - STATIC_ROOT=/app/staticfiles
      - MEDIA_URL=/media/
      - MEDIA_ROOT=/app/media
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - sda-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: sda-postgres-simple
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-sda_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - sda-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sda-redis-simple
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - sda-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  sda-network:
    driver: bridge
